apiVersion: v1
kind: Service
metadata:
  name: node-eks-service
spec:
  type: LoadBalancer                 # AWS will provision an ELB (Elastic Load Balancer)
  selector:
    app: node-eks-app                # This service targets pods with this label
  ports:
    - protocol: TCP
      port: 80                       # Public port
      targetPort: 3000              # Internal container port
